/**
 * GENERATED by scripts/build-api-reference.ts - do not edit by hand.
 * Regenerate with: bun run build-api-reference
 */
import type { ResolvedApiEntry } from './api-reference';

export const API_REFERENCE_RESOLVED: ReadonlyArray<ResolvedApiEntry> = [
  {
    key: 'handler',
    name: '#[handler]',
    ecosystem: 'rust',
    kind: 'macro',
    guideHref: '/documentation/rust-backend',
    language: 'rust',
    signature:
      '#[handler]\nasync fn page(req: Request /* , state, Logger */) -> impl Into<Response>',
    description:
      "Turns an async function into a page/route data handler. The first argument is the Request; remaining arguments are injected application state or a Logger. Its return becomes the page's props.",
    examples: [
      {
        code: '// src/routes/page.rs\n#[handler]\nasync fn home(_req: Request) -> HomeProps {\n    HomeProps { message: "Hello from Rust".into() }\n}',
        lang: 'rust',
        caption:
          "Return a #[Props] struct - it becomes the page component's props:",
      },
      {
        code: '// src/routes/posts/[id]/page.rs\n#[handler]\nasync fn post(req: Request, db: Db) -> PostProps {\n    let id = req.params.get("id").unwrap();\n    PostProps { post: db.load_post(id).await }\n}',
        lang: 'rust',
        caption:
          'Read a dynamic segment, and inject application state by name:',
      },
      {
        code: '#[handler]\nasync fn dashboard(req: Request, logger: Logger) -> Response {\n    logger.info("rendering dashboard");\n    if req.headers.get("cookie").is_none() {\n        return Response::Redirect("/login".into());\n    }\n    DashboardProps::load().await.into()\n}',
        lang: 'rust',
        caption:
          'Return a Response directly to redirect or set a status; log with a Logger:',
      },
    ],
  },
  {
    key: 'api',
    name: '#[api]',
    ecosystem: 'rust',
    kind: 'macro',
    guideHref: '/documentation/api-handlers',
    language: 'rust',
    signature:
      '#[api(GET)] // GET | POST | PUT | PATCH | DELETE\nasync fn route(req: Request) -> impl IntoResponse',
    description:
      'Defines an HTTP API endpoint under src/routes/api, with the method as the macro argument (GET/POST/PUT/PATCH/DELETE). Returns JSON or any axum response.',
    examples: [
      {
        code: '// src/routes/api/health.rs\n#[api(GET)]\nasync fn health(_req: Request) -> Json<Status> {\n    Json(Status { ok: true })\n}',
        lang: 'rust',
        caption: 'A GET endpoint returning JSON:',
      },
      {
        code: '// src/routes/api/subscribe.rs\n#[api(POST)]\nasync fn subscribe(req: Request, db: Db) -> Json<Subscribed> {\n    let input: Subscribe = req.body().unwrap();\n    Json(Subscribed { id: db.insert(input).await })\n}',
        lang: 'rust',
        caption:
          'A POST endpoint reading a typed JSON body, with state injected by name:',
      },
      {
        code: "import { apiClient } from '@ossido-labs/ossido/client';\n\nconst res = await apiClient.get('/api/health');\nconst status = await res.json(); // typed from your Rust route",
        lang: 'tsx',
        caption:
          'Call it from the frontend with the typed client (see createApiClient):',
      },
    ],
  },
  {
    key: 'middleware',
    name: '#[middleware]',
    ecosystem: 'rust',
    kind: 'macro',
    guideHref: '/documentation/middleware',
    language: 'rust',
    signature: '#[middleware]\npub fn my_layer() -> impl Layer<S> + Clone',
    description:
      'Marks a function in a middleware.rs that returns a Tower Layer applied to its route segment. A function returns a single Layer; compose several with a ServiceBuilder.',
    examples: [
      {
        code: '// src/routes/api/middleware.rs\nuse ossido::middleware;\nuse tower_http::cors::{Any, CorsLayer};\n\n#[middleware]\npub fn api_cors() -> CorsLayer {\n    CorsLayer::new().allow_origin(Any)\n}',
        lang: 'rust',
        caption: 'A single layer applied to this segment:',
      },
      {
        code: 'use ossido::middleware;\nuse ossido::tower::{Layer, ServiceBuilder};\nuse tower_http::compression::CompressionLayer;\nuse tower_http::trace::TraceLayer;\n\n#[middleware]\npub fn stack<S>() -> impl Layer<S> + Clone {\n    ServiceBuilder::new()\n        .layer(TraceLayer::new_for_http())\n        .layer(CompressionLayer::new())\n}',
        lang: 'rust',
        caption:
          'Combine several layers - stack them with a ServiceBuilder and return the stack:',
      },
    ],
  },
  {
    key: 'action',
    name: '#[action]',
    ecosystem: 'rust',
    kind: 'macro',
    guideHref: '/documentation/server-actions',
    language: 'rust',
    signature:
      '#[action]                 // generated TS name = camelCased fn name\n#[action(customName)]     // ...or override it with a bare identifier\n#[action("customName")]   // ...or a string literal\nasync fn act(input: In /* , state, Logger, Files, PrevState<T> */) -> Result<Out, ActionError>',
    description:
      '#[ossido::action] - a Next.js-style server action. Marks a function whose typed TypeScript counterpart the build generates (importable, passable to <form action={fn}>, and usable with useActionState). The first non-state, non-logger, non-PrevState argument is the input (decoded from the request body); a PrevState<T> argument opts into the useActionState (prevState, formData) contract.',
    details:
      'The macro reads the function signature as the single source of truth: the first non-state/logger/PrevState argument is the input, a PrevState<T> argument opts into useActionState, a Files argument receives multipart uploads, and any other argument is injected application state (matched by name, like #[handler]). By default the generated TypeScript function is the camelCased Rust name; pass a token stream to the macro to override it.',
    examples: [
      {
        code: '// src/routes/newsletter/actions.rs\n#[action]\nasync fn subscribe(input: Subscribe) -> Result<Subscribed, ActionError> {\n    if !input.email.contains(\'@\') {\n        return Err(ActionError::message("Please enter a valid email"));\n    }\n    Ok(Subscribed { id: 1 })\n}',
        lang: 'rust',
        caption:
          'Define an action in Rust - its return becomes a typed client function:',
      },
      {
        code: "import { subscribe } from '.ossido/actions';\n\nconst { id } = await subscribe({ email: 'ada@example.com' });",
        lang: 'tsx',
        caption:
          'Call it from React, fully typed - input and output inferred from Rust:',
      },
      {
        code: '#[action]\nasync fn upload_avatar(input: AvatarMeta, files: Files, db: Db, logger: Logger)\n    -> Result<Avatar, ActionError>\n{\n    logger.info("uploading avatar");\n    let file = files.get("avatar").ok_or_else(|| ActionError::message("file required"))?;\n    let id = db.store(input.user_id, file.bytes()).await?;\n    Ok(Avatar { id })\n}',
        lang: 'rust',
        caption:
          'Extra arguments are injected by name - application state, a Logger, and Files:',
      },
      {
        code: '#[action(registerUser)]        // or #[action("registerUser")]\nasync fn create_user(input: NewUser) -> Result<Created, ActionError> {\n    Ok(persist(input).await?)\n}',
        lang: 'rust',
        caption: 'Override the generated TypeScript name with a token stream:',
      },
      {
        code: "import { registerUser } from '.ossido/actions';\n\nawait registerUser({ email, name });",
        lang: 'tsx',
      },
      {
        code: "#[action]\nasync fn submit_signup(prev: PrevState<FormState>, input: Subscribe) -> FormState {\n    let attempts = prev.get().map(|s| s.attempts + 1).unwrap_or(1);\n    FormState { ok: input.email.contains('@'), attempts }\n}",
        lang: 'rust',
        caption:
          "A PrevState<T> first argument opts into React's useActionState:",
      },
      {
        code: "import { useActionState } from '@ossido-labs/ossido/actions';\nimport { submitSignup } from '.ossido/actions';\n\nconst [state, formAction, isPending] = useActionState(submitSignup, INITIAL);",
        lang: 'tsx',
      },
    ],
  },
  {
    key: 'static-paths',
    name: '#[static_paths]',
    ecosystem: 'rust',
    kind: 'macro',
    guideHref: '/documentation/rendering',
    language: 'rust',
    signature: '#[static_paths]\nasync fn paths(paths: &mut StaticPaths)',
    description:
      "Mark the function in a dynamic route's page.rs that enumerates the pages to statically generate for that route (Ossido's getStaticPaths). See ossido::StaticPaths.",
    examples: [
      {
        code: '// src/routes/blog/[slug]/page.rs\n#[static_paths]\nasync fn paths(paths: &mut StaticPaths) {\n    for slug in ["hello", "world"] {\n        paths.register(StaticParams::new().param("slug", slug));\n    }\n}',
        lang: 'rust',
        caption: 'A dynamic [slug] route - one page per registered param:',
      },
      {
        code: '// src/routes/docs/[...path]/page.rs\n#[static_paths]\nasync fn paths(paths: &mut StaticPaths) {\n    // → /docs/intro\n    paths.register(StaticParams::new().catchall("path", vec!["intro".into()]));\n    // → /docs/guides/first-app\n    paths.register(\n        StaticParams::new().catchall("path", vec!["guides".into(), "first-app".into()]),\n    );\n}',
        lang: 'rust',
        caption:
          'A catch-all [...path] route - each catchall is an ordered list of segments:',
      },
    ],
  },
  {
    key: 'type-macro',
    name: '#[Type]',
    ecosystem: 'rust',
    kind: 'macro',
    guideHref: '/documentation/typescript',
    language: 'rust',
    signature:
      '#[Type]\npub struct Name { /* fields → generated TypeScript */ }',
    description:
      '#[ossido::Type] - bundle serde::{Serialize, Deserialize} onto a struct or enum and generate its TypeScript type (exported from the "@ossido-labs/ossido/types" module). Replaces the old #[derive(Serialize, Deserialize, Type)].',
    examples: [
      {
        code: '#[Type]\npub struct User { pub id: u64, pub name: String }',
        lang: 'rust',
      },
      {
        code: "import type { User } from '@ossido-labs/ossido/types';",
        lang: 'ts',
        caption: 'The generated TypeScript is importable:',
      },
    ],
  },
  {
    key: 'props-macro',
    name: '#[Props]',
    ecosystem: 'rust',
    kind: 'macro',
    guideHref: '/documentation/rust-backend',
    language: 'rust',
    signature:
      '#[Props]\npub struct PageProps { /* becomes the page component props */ }',
    description:
      "#[ossido::Props] - bundle serde::{Serialize, Deserialize} and register the struct for TypeScript generation (everything #[Type] does), plus a From<Self> for ossido::Response impl so it can be returned directly from a #[ossido::handler]. The struct must be 'static.",
    examples: [
      {
        code: '#[Props]\npub struct HomeProps { pub message: String }\n\n#[handler]\nasync fn home(_req: Request) -> HomeProps {\n    HomeProps { message: "Hi".into() }\n}',
        lang: 'rust',
      },
    ],
  },
  {
    key: 'environment',
    name: '#[Environment]',
    ecosystem: 'rust',
    kind: 'macro',
    guideHref: '/documentation/environment-variables',
    language: 'rust',
    signature:
      'use ossido::Environment;\n\n#[allow(non_snake_case)]\n#[Environment]\npub struct Environment {\n    #[public]\n    API_URL: String,\n    ANALYTICS_ENABLED: Option<bool>,\n    DATABASE_URL: String,\n}',
    description:
      "#[ossido::Environment] - mark the project's typed environment schema. See environment::environment_attr for the full contract (typed FromStr parsing, required vs Option fields, the #[public] helper, and the generated from_env / public-JSON methods). Read fields in Rust via ossido::get_env!; TypeScript types for the public fields are generated only when this struct exists.",
    details:
      'The struct becomes the single source of truth for configuration: fields are parsed and validated once at startup, and only the fields you mark `#[public]` are exposed to the frontend (with generated TypeScript types). The whole feature is optional - define no `Environment` struct and nothing is generated.\n\nName fields in `SCREAMING_SNAKE` so the key is identical everywhere - the OS variable, `get_env!`, and `getEnv`. A non-`Option` field is required (a missing or unparseable value panics at startup); an `Option<T>` field is optional. Read fields in Rust with `get_env!`, and public fields on the frontend with `getEnv`.',
    examples: [
      {
        code: "// src/env.rs\nuse ossido::Environment;\n\n#[allow(non_snake_case)]\n#[Environment]\npub struct Environment {\n    // Public - available on the client via getEnv('API_URL').\n    #[public]\n    API_URL: String,\n\n    // Public, typed + optional - getEnv('ANALYTICS_ENABLED') is `boolean | null`.\n    #[public]\n    ANALYTICS_ENABLED: Option<bool>,\n\n    // Server-only secret - never leaves the backend.\n    DATABASE_URL: String,\n}",
        lang: 'rust',
        caption: 'Define the schema (convention: `src/env.rs`):',
      },
    ],
  },
  {
    key: 'get-env',
    name: 'get_env!',
    ecosystem: 'rust',
    kind: 'macro',
    guideHref: '/documentation/environment-variables',
    language: 'rust',
    signature:
      'use ossido::get_env;\n\nlet db = get_env!(DATABASE_URL);                    // String\nlet raw = get_env!(ANALYTICS_ENABLED);              // Option<bool>\nlet analytics = get_env!(ANALYTICS_ENABLED, false); // bool',
    description:
      'Reads a field from the typed Environment singleton, returning a parsed copy of its value. A second argument provides a fallback that collapses an Option<T> field to a concrete T. If the project defines no Environment struct the accessor is never generated, so the macro fails to compile at the call site.',
    examples: [
      {
        code: 'use ossido::get_env;\n\nlet db = get_env!(DATABASE_URL); // String\nlet flag = get_env!(ANALYTICS_ENABLED); // Option<bool>',
        lang: 'rust',
        caption:
          "Read any field - public or private - from your `Environment` struct. The value comes back parsed to the field's Rust type:",
      },
      {
        code: '// ANALYTICS_ENABLED: Option<bool>\nlet analytics = get_env!(ANALYTICS_ENABLED, false); // bool',
        lang: 'rust',
        caption:
          'Pass a second argument to collapse an `Option<T>` field to a concrete `T`, using the fallback when the variable is unset (a fallback on a required field is a type error):',
      },
    ],
  },
  {
    key: 'public',
    name: '#[public]',
    ecosystem: 'rust',
    kind: 'macro',
    guideHref: '/documentation/environment-variables',
    language: 'rust',
    signature:
      "#[Environment]\npub struct Environment {\n    #[public]\n    API_URL: String, // exposed as getEnv('API_URL')\n}",
    description:
      'An inert helper attribute on an Environment field that exposes it to the frontend. Public fields are serialized into the SSR payload and the browser global that getEnv reads; every other field stays server-only.',
    examples: [
      {
        code: "use ossido::Environment;\n\n#[allow(non_snake_case)]\n#[Environment]\npub struct Environment {\n    #[public]\n    API_URL: String, // getEnv('API_URL')\n\n    DATABASE_URL: String, // server-only\n}",
        lang: 'rust',
        caption:
          'Mark the fields you want available in the browser. Only `#[public]` fields are serialized to the client - secrets and connection strings left unmarked never leave the server:',
      },
    ],
  },
  {
    key: 'set-error-handler',
    name: 'set_error_handler',
    ecosystem: 'rust',
    kind: 'function',
    guideHref: '/documentation/error-handling',
    language: 'rust',
    signature:
      "pub fn set_error_handler<F, Fut>(handler: F) where F: Fn(ErrorContext) -> Fut + Send + Sync + 'static, Fut: Future<Output = Option<AxumResponse>> + Send + 'static",
    description:
      "Register the process-wide error handler. Call this once, early (typically from src/app.rs main()); a later call is ignored (the first registration wins). The handler runs on every error thrown by a request handler. Return Some(response) to send a custom HTTP response, or None to fall back to Ossido's default error page / JSON. See the module docs.",
    details:
      'Register once, early (typically from src/app.rs main()), before the server starts - the first registration wins. The closure runs for every error thrown by a handler or action.',
    examples: [
      {
        code: '// src/app.rs\nset_error_handler(|ctx: ErrorContext| async move {\n    report(&ctx.error).await;\n    None // None → Ossido renders its default error page / JSON\n});',
        lang: 'rust',
        caption:
          'Report every error, then fall back to the default error page:',
      },
      {
        code: 'use ossido::axum::{http::StatusCode, response::IntoResponse, Json};\n\nset_error_handler(|ctx: ErrorContext| async move {\n    report(&ctx.error).await;\n    Some((StatusCode::INTERNAL_SERVER_ERROR, Json(ErrorBody { id: ctx.error_id })).into_response())\n});',
        lang: 'rust',
        caption:
          'Return Some(response) to override the default 500 with your own:',
      },
    ],
  },
  {
    key: 'request',
    name: 'Request',
    ecosystem: 'rust',
    kind: 'struct',
    guideHref: '/documentation/rust-backend',
    language: 'rust',
    signature:
      'pub struct Request {\n    pub uri: Uri,\n    /// Wrapped in `Arc` so cloning a `Request` (once per page + once per\n    /// ascendant layout handler) shares the header map instead of deep-copying\n    /// it. Read access (`req.headers.get(..)`) is unchanged via `Deref`.\n    pub headers: Arc<HeaderMap>,\n    pub params: HashMap<String, String>,\n    body: Option<Vec<u8>>,\n}',
    description:
      'The incoming HTTP request in a handler or action: URI, headers, route params, and typed body parsing - body::<T>() decodes a JSON body, form_data::<T>() decodes a url-encoded form. Both return Result<T, BodyParseError>.',
    examples: [
      {
        code: '#[handler]\nasync fn show(req: Request) -> PostProps {\n    let id = req.params.get("id").unwrap();\n    let lang = req.headers.get("accept-language");\n    PostProps { post: load(id).await }\n}',
        lang: 'rust',
        caption: 'Read route params and headers:',
      },
      {
        code: '#[api(POST)]\nasync fn create(req: Request) -> Json<Created> {\n    let input: NewPost = req.body().unwrap(); // deserialized from JSON\n    Json(Created { id: save(input).await })\n}',
        lang: 'rust',
        caption: 'Parse a JSON body with body::<T>():',
      },
      {
        code: '#[api(POST)]\nasync fn login(req: Request) -> Response {\n    let form: LoginForm = req.form_data().unwrap();\n    authenticate(&form).await\n}',
        lang: 'rust',
        caption:
          'Parse a url-encoded form (application/x-www-form-urlencoded) with form_data::<T>():',
      },
    ],
  },
  {
    key: 'action-error',
    name: 'ActionError',
    ecosystem: 'rust',
    kind: 'struct',
    guideHref: '/documentation/server-actions#error-handling',
    language: 'rust',
    signature:
      'pub struct ActionError {\n    pub message: String,\n    /// Optional per-field validation messages (e.g. `{ "email": "required" }`).\n    #[serde(skip_serializing_if = "Option::is_none")]\n    pub fields: Option<HashMap<String, String>>,\n}',
    description:
      'A domain error returned from an action as Err(ActionError). Serialized into the { "error": ... } envelope (HTTP 422) and surfaced on the client as a thrown OssidoActionError. Distinct from a panic, which is caught and routed through the framework\'s ServerError overlay.',
    examples: [
      {
        code: 'return Err(ActionError::message("Please enter a valid email"));\n// or with per-field messages:\nreturn Err(ActionError::with_fields("Validation failed", fields));',
        lang: 'rust',
      },
    ],
  },
  {
    key: 'prev-state',
    name: 'PrevState',
    ecosystem: 'rust',
    kind: 'struct',
    guideHref: '/documentation/server-actions#stateful-actions-useactionstate',
    language: 'rust',
    signature: 'pub struct PrevState<T>(Option<T>);',
    description:
      "The previous useActionState state, round-tripped from the client. None on the first render (or when the action is called imperatively without a prior state). A PrevState<T> parameter is how an action opts into React's (prevState, formData) => newState contract. The wrapped value is untrusted client input - never use it as authorization state.",
    examples: [
      {
        code: "#[action]\nasync fn submit(prev: PrevState<FormState>, input: Subscribe) -> FormState {\n    let attempts = prev.get().map(|s| s.attempts + 1).unwrap_or(1);\n    FormState { attempts, ok: input.email.contains('@') }\n}",
        lang: 'rust',
      },
    ],
  },
  {
    key: 'files',
    name: 'Files',
    ecosystem: 'rust',
    kind: 'struct',
    guideHref: '/documentation/server-actions#file-uploads-multipart',
    language: 'rust',
    signature: 'pub struct Files(HashMap<String, Vec<UploadedFile>>);',
    description:
      'The files uploaded by a multipart/form-data server action, keyed by form field name. Declare a Files parameter on an #[action] to receive them; it is empty for JSON / URL-encoded requests.',
    examples: [
      {
        code: '#[action]\nasync fn upload(files: Files) -> Result<(), ActionError> {\n    let file = files.get("avatar").ok_or_else(|| ActionError::message("required"))?;\n    save(file.filename(), file.bytes()).await;\n    Ok(())\n}',
        lang: 'rust',
        caption: 'A single required file:',
      },
      {
        code: 'for photo in files.get_all("photos") {\n    store(photo.filename(), photo.bytes()).await;\n}',
        lang: 'rust',
        caption:
          'Multiple files under one field (<input type="file" multiple>):',
      },
    ],
  },
  {
    key: 'uploaded-file',
    name: 'UploadedFile',
    ecosystem: 'rust',
    kind: 'struct',
    guideHref: '/documentation/server-actions#file-uploads-multipart',
    language: 'rust',
    signature:
      'pub struct UploadedFile {\n    filename: String,\n    content_type: Option<String>,\n    bytes: Bytes,\n}',
    description: 'A file uploaded via a multipart/form-data server action.',
    examples: [
      {
        code: 'let file = files.get("avatar").unwrap();\nprintln!("{} - {} bytes ({:?})", file.filename(), file.len(), file.content_type());\nlet bytes = file.into_bytes();',
        lang: 'rust',
      },
    ],
  },
  {
    key: 'error-context',
    name: 'ErrorContext',
    ecosystem: 'rust',
    kind: 'struct',
    guideHref: '/documentation/error-handling',
    language: 'rust',
    signature:
      'pub struct ErrorContext {\n    /// The structured error (name, message, stack, source).\n    pub error: ServerError,\n    /// The request that failed - call `.pathname()`, read `.params`, etc.\n    pub request: Request,\n    /// Whether the server is running in development or production.\n    pub mode: Mode,\n    /// A unique id for this occurrence, so a report (e.g. a Sentry event) and a\n    /// user-facing page can be correlated.\n    pub error_id: String,\n}',
    description:
      'Everything a registered error handler is given about a failed request. Owned (not borrowed) so the handler may hold it across an .await.',
    examples: [
      {
        code: 'set_error_handler(|ctx: ErrorContext| async move {\n    eprintln!("{} on {}", ctx.error, ctx.request.uri);\n    None\n});',
        lang: 'rust',
      },
    ],
  },
  {
    key: 'static-paths-type',
    name: 'StaticPaths',
    ecosystem: 'rust',
    kind: 'struct',
    guideHref: '/documentation/rendering',
    language: 'rust',
    signature: 'pub struct StaticPaths(Vec<StaticParams>);',
    description:
      'The full set of pages to statically generate for a dynamic route. A #[ossido::static_paths] function receives this borrowed and registers one entry per page.',
    details:
      'Collects the set of pages to generate for a dynamic route. Register one StaticParams per page; each carries a value for every dynamic slot in the route path.',
    examples: [
      {
        code: '// src/routes/blog/[slug]/page.rs\n#[static_paths]\nasync fn paths(paths: &mut StaticPaths) {\n    paths.register(StaticParams::new().param("slug", "hello"));\n}',
        lang: 'rust',
        caption: 'One dynamic segment - register one page per value:',
      },
      {
        code: '// src/routes/[lang]/blog/[slug]/page.rs\n#[static_paths]\nasync fn paths(paths: &mut StaticPaths) {\n    for lang in ["en", "fr"] {\n        for slug in ["hello", "world"] {\n            paths.register(\n                StaticParams::new().param("lang", lang).param("slug", slug),\n            );\n        }\n    }\n}',
        lang: 'rust',
        caption:
          "Multiple params - one StaticParams per page carries every segment's value:",
      },
    ],
  },
  {
    key: 'static-params',
    name: 'StaticParams',
    ecosystem: 'rust',
    kind: 'struct',
    guideHref: '/documentation/rendering',
    language: 'rust',
    signature: 'pub struct StaticParams(HashMap<String, SegmentValue>);',
    description:
      'The parameters for a single generated page: a map from each dynamic slot name to its SegmentValue. Built through the closure passed to StaticPaths::register.',
    examples: [
      {
        code: 'StaticParams::new()\n    .param("lang", "en")\n    .catchall("path", vec!["docs".into(), "intro".into()])',
        lang: 'rust',
      },
    ],
  },
  {
    key: 'logger',
    name: 'Logger',
    ecosystem: 'rust',
    kind: 'struct',
    guideHref: '/documentation/ossido-application',
    language: 'rust',
    signature: 'pub struct Logger {\n    path: String,\n}',
    description:
      'A request-scoped, handler-facing logger. Declare a logger parameter on a #[handler] / #[api] function and the framework provides it automatically - it does **not** need to be added to ApplicationState, and it works whether or not the app has custom state: ignore #[ossido::handler] async fn get_pokemon(req: Request, fetch: Client, logger: ossido::Logger) -> Response { logger.info("fetching a pokemon"); // ... } Its methods emit BE log lines (in the active pretty / json format) tagged with the request path, so a handler\'s logs are tied to the request.',
    examples: [
      {
        code: '#[handler]\nasync fn home(_req: Request, logger: Logger) -> HomeProps {\n    logger.info("loading home");\n    HomeProps::default()\n}',
        lang: 'rust',
      },
    ],
  },
  {
    key: 'response',
    name: 'Response',
    ecosystem: 'rust',
    kind: 'enum',
    guideHref: '/documentation/rust-backend',
    language: 'rust',
    signature:
      'pub enum Response {\n    Redirect(String),\n    Props(Props),\n    // TODO: improve this tuple to support a more generic IntoResponse\n    Custom((StatusCode, HeaderMap, String)),\n}',
    description:
      "A handler's return value: page Props, a redirect, or a custom axum response. Most handlers return a #[Props] struct and never build this directly.",
    examples: [
      {
        code: '#[handler]\nasync fn go(_req: Request) -> Response {\n    Response::Redirect("/login".into())\n}',
        lang: 'rust',
      },
    ],
  },
  {
    key: 'segment-value',
    name: 'SegmentValue',
    ecosystem: 'rust',
    kind: 'enum',
    guideHref: '/documentation/rendering',
    language: 'rust',
    signature:
      'pub enum SegmentValue {\n    /// A `[param]` slot - exactly one URL segment.\n    One(String),\n    /// A `[...catchall]` slot - zero or more URL segments, in order.\n    Many(Vec<String>),\n}',
    description:
      'The value bound to one dynamic slot of a route: a single URL segment (param) or an ordered list of segments (...catchall). Serialised *untagged*, so a single value is a JSON string and a catch-all is a JSON array - matching how the build substitutes each into the route pattern (and how Next represents catch-all params).',
    examples: [
      {
        code: 'match value {\n    SegmentValue::One(seg) => { /* a [param] slot - one segment */ }\n    SegmentValue::Many(parts) => { /* a [...catchall] slot - many segments */ }\n}',
        lang: 'rust',
      },
    ],
  },
  {
    key: 'link',
    name: 'Link',
    ecosystem: 'react',
    kind: 'component',
    guideHref: '/documentation/react-frontend#client-navigation',
    language: 'tsx',
    signature: 'function Link(componentProps: OssidoLinkProps): JSX.Element;',
    description:
      'Client-side navigation link - preload-aware (loads the route on hover/viewport), with optional scroll, replace, and View Transition control. Keeps navigation within the SPA.',
    examples: [
      {
        code: 'import { Link } from \'@ossido-labs/ossido\';\n\n<Link href="/guides" preload>\n  Guides\n</Link>;',
        lang: 'tsx',
      },
    ],
  },
  {
    key: 'form',
    name: 'Form',
    ecosystem: 'react',
    kind: 'component',
    guideHref: '/documentation/server-actions',
    language: 'tsx',
    signature:
      'function Form<Input, Output>(props: {\n  action: ActionFn<Input, Output> | StatefulActionFn<Input, Output>\n  onSubmit?: (result: Output) => void\n} & FormHTMLAttributes): ReactNode',
    description:
      'A <form> wired to a server action with progressive enhancement. When hydrated, submission is intercepted and the action is called with FormData. With JS disabled, the rendered action={fn.url} makes it a native POST, and the server responds with a 303 Post/Redirect/Get.',
    details:
      'Renders a real <form method="post" action={fn.url}>. When hydrated it intercepts the submit and calls the action with the form\'s FormData; with JS disabled the browser does a native POST and the server replies with a 303 redirect. Prefer <Form> over React\'s own <form action={fn}> when you want that no-JS fallback. Set encType="multipart/form-data" for file uploads.',
    examples: [
      {
        code: 'import { Form } from \'@ossido-labs/ossido/actions\';\nimport { subscribe } from \'.ossido/actions\';\n\n<Form action={subscribe} encType="multipart/form-data">\n  <input name="email" type="email" />\n  <input name="avatar" type="file" />\n  <button>Subscribe</button>\n</Form>;',
        lang: 'tsx',
        caption:
          'Progressive-enhancement form - works with or without JavaScript:',
      },
    ],
  },
  {
    key: 'ossido-scripts',
    name: 'OssidoScripts',
    ecosystem: 'react',
    kind: 'component',
    guideHref: '/documentation/react-frontend',
    language: 'tsx',
    signature: 'function OssidoScripts(): JSX.Element;',
    description:
      "Injects the serialized server payload and the framework's client scripts. Render once in the root layout's <body>.",
    examples: [
      {
        code: "import { OssidoScripts } from '@ossido-labs/ossido';\n\nexport default function RootLayout({ children }) {\n  return (\n    <html>\n      <body>\n        {children}\n        <OssidoScripts />\n      </body>\n    </html>\n  );\n}",
        lang: 'tsx',
      },
    ],
  },
  {
    key: 'use-router',
    name: 'useRouter',
    ecosystem: 'react',
    kind: 'hook',
    guideHref: '/documentation/react-frontend',
    language: 'tsx',
    signature: 'const useRouter: () => UseRouterResult;',
    description:
      'Access the router instance for programmatic navigation and the current location.',
    examples: [
      {
        code: "import { useRouter } from '@ossido-labs/ossido';\n\nconst { pathname } = useRouter();",
        lang: 'tsx',
      },
    ],
  },
  {
    key: 'use-action-state',
    name: 'useActionState',
    ecosystem: 'react',
    kind: 'hook',
    guideHref: '/documentation/server-actions#stateful-actions-useactionstate',
    language: 'tsx',
    signature:
      'const [state, formAction, isPending] = useActionState(action, initialState)',
    description:
      "React's hook for stateful actions, re-exported so there's one import site. Pass a stateful Ossido action (one with a PrevState argument) and its initial state.",
    examples: [
      {
        code: "import { useActionState } from '@ossido-labs/ossido/actions';\nimport { submitSignup } from '.ossido/actions';\n\nconst [state, formAction, isPending] = useActionState(submitSignup, INITIAL);",
        lang: 'tsx',
      },
    ],
  },
  {
    key: 'use-form-status',
    name: 'useFormStatus',
    ecosystem: 'react',
    kind: 'hook',
    guideHref: '/documentation/server-actions',
    language: 'tsx',
    signature: 'const { pending, data, method, action } = useFormStatus()',
    description:
      "React DOM's hook for the pending state of the nearest parent <form>, re-exported for convenience inside action forms.",
    examples: [
      {
        code: "import { useFormStatus } from '@ossido-labs/ossido/actions';\n\nfunction Submit() {\n  const { pending } = useFormStatus();\n  return <button disabled={pending}>Save</button>;\n}",
        lang: 'tsx',
      },
    ],
  },
  {
    key: 'dynamic',
    name: 'dynamic',
    ecosystem: 'react',
    kind: 'function',
    guideHref: '/documentation/react-frontend',
    language: 'tsx',
    signature:
      'function dynamic<T = object>(importFn: Loader<T>, opts?: DynamicOptions): ComponentType<T>;',
    description:
      'This function lets you dynamically import a component. It uses React.lazy() with Suspense under the hood.',
    examples: [
      {
        code: "import { dynamic } from '@ossido-labs/ossido';\n\nconst Chart = dynamic(() => import('./Chart'), { ssr: false });",
        lang: 'tsx',
      },
    ],
  },
  {
    key: 'create-api-client',
    name: 'createApiClient',
    ecosystem: 'react',
    kind: 'function',
    guideHref: '/documentation/api-client',
    language: 'tsx',
    signature:
      'function createApiClient(options?: CreateApiClientOptions): ApiClient;',
    description:
      'Create an ApiClient, optionally with a base URL and default options.',
    examples: [
      {
        code: "import { createApiClient } from '@ossido-labs/ossido/client';\n\nconst api = createApiClient({ baseUrl: 'https://example.com' });\nconst res = await api.get('/api/user', { params: { id: '1' } });",
        lang: 'tsx',
      },
    ],
  },
  {
    key: 'getenv',
    name: 'getEnv',
    ecosystem: 'react',
    kind: 'function',
    guideHref: '/documentation/environment-variables',
    language: 'tsx',
    signature:
      'function getEnv<K extends keyof PublicEnv>(key: K): PublicEnv[K];\nfunction getEnv<K extends keyof PublicEnv>(\n  key: K,\n  fallback: NonNullable<PublicEnv[K]>,\n): NonNullable<PublicEnv[K]>;',
    description:
      'Read a public environment variable by key, returning a typed copy of its value. Throws if no public environment is available - i.e. the project defines no #[ossido::Environment] struct (the Rust equivalent, get_env!, is a compile error in that case) - or if the key is not a known public variable.',
    examples: [
      {
        code: "import { getEnv } from '@ossido-labs/ossido/env';\n\nconst apiUrl = getEnv('API_URL'); // string\nconst analytics = getEnv('ANALYTICS_ENABLED'); // boolean | null",
        lang: 'tsx',
        caption:
          'Only `#[public]` fields are available, and their types are generated into `.ossido/types.ts`, so keys and value types are checked. `getEnv` works during SSR and on the client.',
      },
      {
        code: "const enabled = getEnv('ANALYTICS_ENABLED', false); // boolean",
        lang: 'tsx',
        caption:
          "A second argument is a fallback that collapses an optional value to a concrete `T`. It's returned whenever the value is absent (an optional variable unset, or no public environment available), so this form never throws:",
      },
    ],
  },
  {
    key: 'ossido-action-error',
    name: 'OssidoActionError',
    ecosystem: 'react',
    kind: 'class',
    guideHref: '/documentation/server-actions#error-handling',
    language: 'tsx',
    signature:
      'class OssidoActionError extends Error {\n  message: string\n  fields?: Record<string, string>\n}',
    description:
      'Thrown by an action call when the server returns an error (or panics).',
    examples: [
      {
        code: "import { OssidoActionError } from '@ossido-labs/ossido/actions';\n\ntry {\n  await createUser(input);\n} catch (e) {\n  if (e instanceof OssidoActionError) console.log(e.message, e.fields);\n}",
        lang: 'tsx',
      },
    ],
  },
  {
    key: 'api-client',
    name: 'apiClient',
    ecosystem: 'react',
    kind: 'constant',
    guideHref: '/documentation/api-client',
    language: 'tsx',
    signature: 'const apiClient: ApiClient;',
    description: 'The default client - global fetch, relative paths.',
    examples: [
      {
        code: "import { apiClient } from '@ossido-labs/ossido/client';\n\nconst res = await apiClient.get('/api/health');\nconst data = await res.json();",
        lang: 'tsx',
      },
    ],
  },
  {
    key: 'ossido-page',
    name: 'OssidoPage',
    ecosystem: 'react',
    kind: 'type',
    guideHref: '/documentation/typescript',
    language: 'tsx',
    signature:
      'type OssidoPage<Path extends keyof RouteProps> = (props: RouteProps[Path]) => ReactNode',
    description:
      "Types a page component so its props are exactly the matching Rust handler's return type, keyed by the route path.",
    examples: [
      {
        code: "import type { OssidoPage } from '@ossido-labs/ossido/types';\n\nconst Home: OssidoPage<'/'> = ({ message }) => <h1>{message}</h1>;\nexport default Home;",
        lang: 'tsx',
      },
    ],
  },
  {
    key: 'ossido-layout-props',
    name: 'OssidoLayoutProps',
    ecosystem: 'react',
    kind: 'type',
    guideHref: '/documentation/react-frontend',
    language: 'tsx',
    signature: 'interface OssidoLayoutProps {\n    children: ReactNode;\n}',
    description:
      'Props for a layout component - { children } for the wrapped subtree.',
    examples: [
      {
        code: "import type { OssidoLayoutProps } from '@ossido-labs/ossido';\n\nexport default function Layout({ children }: OssidoLayoutProps) {\n  return <section>{children}</section>;\n}",
        lang: 'tsx',
      },
    ],
  },
  {
    key: 'ossido-error-props',
    name: 'OssidoErrorProps',
    ecosystem: 'react',
    kind: 'type',
    guideHref: '/documentation/error-handling',
    language: 'tsx',
    signature:
      'interface OssidoErrorProps {\n    error: Error;\n    reset: () => void;\n}',
    description:
      'Props passed to a user error.tsx component (and the default error UI).',
    examples: [
      {
        code: "import type { OssidoErrorProps } from '@ossido-labs/ossido';\n\nexport default function Error({ error, reset }: OssidoErrorProps) {\n  return <button onClick={reset}>Try again</button>;\n}",
        lang: 'tsx',
      },
    ],
  },
  {
    key: 'ossido-config',
    name: 'OssidoConfig',
    ecosystem: 'react',
    kind: 'type',
    guideHref: '/documentation/configuration',
    language: 'tsx',
    signature:
      "interface OssidoConfig {\n    server?: Partial<OssidoConfigServer>;\n    vite?: {\n        alias?: AliasOptions;\n        css?: CSSOptions;\n        optimizeDeps?: DepOptimizationOptions;\n        plugins?: Array<PluginOption>;\n    };\n    logging?: OssidoConfigLogging;\n    dev?: OssidoConfigDev;\n    ssr?: OssidoConfigSsr;\n    /**\n     * Default build output mode. Default `'server'`.\n     * - `'server'`: build the SSR server (`ossido build`).\n     * - `'static'`: statically generate the site (equivalent to `ossido build\n     *   --static`).\n     *\n     * The `--static` / `--server` CLI flags override this per invocation.\n     */\n    output?: OssidoConfigOutput;\n    /** Build lifecycle hooks (`ossido build`, both output modes; not `dev`). */\n    build?: OssidoConfigBuild;\n    /**\n     * Override which `.env` file(s) are loaded, as a path or array of paths\n     * (relative to the project root, loaded in order - a later file overrides an\n     * earlier one). When set, this **replaces** the default\n     * `.env` / `.env.local` / `.env.[mode]` cascade. Leave unset to keep the\n     * default cascade.\n     *\n     * Only meaningful alongside an `#[ossido::Environment]` struct, which defines\n     * the typed schema these variables populate.\n     */\n    env?: string | Array<string>;\n    /**\n     * Animate client-side navigations with the browser\n     * [View Transitions API](https://developer.mozilla.org/en-US/docs/Web/API/View_Transitions_API).\n     * Default `false`. When enabled, `push`/`replace`/`<Link>`/back-forward\n     * navigations run inside `document.startViewTransition` (a crossfade by\n     * default; customise with `view-transition-name` / `::view-transition-*` CSS).\n     * No-ops where unsupported or under `prefers-reduced-motion`; override per\n     * navigation with `push(path, { viewTransition: false })` or\n     * `<Link viewTransition={false}>`.\n     */\n    viewTransitions?: boolean;\n}",
    description:
      'The ossido.config.ts shape: server options, Vite passthrough, logging, SSR render threads, output mode, build hooks, and view transitions.',
    examples: [
      {
        code: "import type { OssidoConfig } from '@ossido-labs/ossido/config';\n\nconst config: OssidoConfig = {\n  output: 'static',\n  server: { port: 3000 },\n};\nexport default config;",
        lang: 'ts',
      },
    ],
  },
];
